<?php
include ('header.html');
?>

<section class="banner-area relative"  id="home" style="padding:0;margin:0;height:45vh;background: url(img/terminos.jpg) center;display: flex;justify-content: center;align-items: center;">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center" style="width:100%;">
      <div class="about-content col-lg-12" style="width:100%;">
        <h1 id="pagDif10" class="text-white" style="width:100%;background:rgba(93,97,99, 0.35);height:100px;display: flex;justify-content: center;align-items: center;"></h1>
      </div>
    </div>
  </div>
</section>


<section class="service-area section-gap" style="margin:0;padding:45px">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-6">
        <div class="single-service">
          <blockquote class="generic-blockquote" style="text-align:justify;line-height:2.2;font-size:14px">
            <h5 style="font-weight:bold">USO DEL SITIO</h5><br>
            Los términos y condiciones que se detallan a continuación regulan el uso de los servicios en la Página web www.lamhi.com.mx (en adelante, la "Página") de GRUPO LAMHI (“Lamhi”) que pone a disposición del usuario.<br>
            <h5 style="font-weight:bold"><br>1. DEFINICIONES</h5><br>
            Para los efectos del presente documento, cuando se utilicen los siguientes términos, y la primera de sus letras sea mayúscula (ya sea en la forma singular o plural), tendrán el significado que se señala a continuación:<br>
            Usuario: Persona física o moral que hace uso del Servicio.<br>
            Servicio: Servicio ofrecido por Grupo Lamhi, conforme al cual los Usuarios pueden hacer uso de los Contenidos que existen en la Página para ver y/o escuchar y/o enviar y/o, en algunos casos, realizar descargas de cualquier tipo de video, audio, texto, imágenes, animaciones, videos u otros materiales digitales desde distintas terminales de  recepción y vectores de telecomunicaciones.<br>
            Página web: Sitio Web localizado en la dirección de Internet www.lamhi.com.mx a través del cual se ofrece el Servicio, y en donde además existen ligas de acceso a otros sitios y/o portales de Internet en los que existen diversos Contenidos que se encuentran a disposición de los Usuarios.<br>
            Cookie:Es un pequeño archivo que es almacenado en el disco duro de la computadora del Usuario y que contiene caracteres particulares del Usuario así como información sobre el uso que éste da al sitio.<br>
            Contenidos:Es cualquier tipo de video, audio, textos, fotografías, gráficos, imágenes, iconos, tecnología, software, links, diseño gráfico, códigos fuente, y demás materiales audiovisuales, digitales o sonoros, , propiedad de Grupo Lamhiy/o de cualquier tercero.<br>
            <h5 style="font-weight:bold"><br>2. OBJETO</h5><br>
            La utilización delaPáginale atribuye a Ud. la condición de Usuario delaPáginae implica la aceptaciónplena y sin reservas de todas y cada una de las disposiciones incluidas en este documento así como a cualquier otra disposición, requerimiento, lineamiento o similar, que sea de tiempo en tiempo establecido en laPáginadirectamente o a través de los vínculos que muestren dicha información.<br>
            El Servicio es un servicio exclusivamente para uso personal por parte del Usuario, por lo que de ninguna forma el Usuario podrá utilizarlo con fines comerciales ya sean propios o de terceros o de cualquier otro tipo, salvo acuerdo previo y por escrito entre Grupo Lamhi y el Usuario, por lo que de manera enunciativa y no limitativa, el Usuario deberá abstenerse de: (i) comercializar, vender, revender, transmitir o retransmitir el Servicio.<br>
            La utilización de ciertos Servicios ofrecidos a los Usuarios a través delaPáginase encuentra sometida a condiciones particulares (en adelante, las "Condiciones Particulares") que, según los casos, sustituyen, completan y/o modifican los presentes términos y condiciones de uso delaPágina. Por lo tanto, con anterioridad a la utilización de dichos Servicios, el Usuario también ha de leer atentamente las correspondientes Condiciones Particulares.<br>
            Cualquier nueva aplicación que permita aumentar o mejorar el Servicio, que sea propiedad delPrestador y/o de cualquier tercero, estará sujeta a los términos y condiciones establecidas en este instrumento, así como a aquellas que el tercero determine, salvo en aquellos casos en que expresamente se establezca lo contrario.<br>
            <h5 style="font-weight:bold"><br>3. CONDICIONES DE ACCESO Y UTILIZACIÓN DE LA PÁGINA </h5><br>
            <h5><br>3.1. Carácter gratuito del acceso y utilización de la Página</h5><br>
            El acceso a la Página no tendrá costo. No obstante, algunos de los Servicios suministrados por Grupo Lamhi y/o por terceros a través de la Página, están sujetos al pago de un precio, en la forma que se determine en las correspondientes Condiciones Particulares.<br>
            <h5 style="font-weight:bold"><br>3.2. Registro de Usuario </h5><br>
            El acceso a la Página generalmente no exige la suscripción previa de los Usuarios. No obstante, algunos Servicios podrán requerir del correspondiente registro de Usuario, por lo que éste deberá proporcionar la información que le sea requerida en la forma expresamente indicada en el propio servicio o en las Condiciones Particulares, a efecto de que pueda hacer uso de dicho servicio (la “Cuenta de Servicio”).<br>

            <h5 style="font-weight:bold"><br>3.3. Veracidad de la información</h5><br>
            Toda la información que facilite el Usuario a través de los Servicios deberá ser veraz. A estos efectos, el Usuario garantiza la autenticidad de todos aquellos datos que comunique como consecuencia de su registro en la Cuenta de Servicio, y en tal virtud se responsabiliza de cualquier información que transmita a través del Servicio. Derivado de lo anterior, el Usuario libera expresamente a Grupo Lamhi de cualquier responsabilidad derivada de accesos no autorizados, robo, daño, destrucción o desviación de información, archivos o programas propiedad del Usuario que se relacionen de manera directa o indirecta con el Servicio.<br>
            Asimismo, y en caso de que Grupo Lamhi tenga conocimiento u observe que la información proporcionada durante el uso de los Servicios o la apertura de la Cuenta de Servicio, son en su totalidad o en parte, incorrectos, imprecisos, falsos o incompletos, Grupo Lamhi podrá cancelar su cuenta y bloquear cualquier nuevo uso de dichos Servicios, sin perjuicio de cualquier otro tipo de reclamación que sea su voluntad interponer.<br>

            <h5 style="font-weight:bold"><br>3.4. Menores de edad </h5><br>
            Para hacer uso de los Servicios, los menores de edad deben obtener previamente permiso de sus padres, tutores o representantes legales, quienes serán considerados responsables de todos los actos realizados por los menores a su cargo. Derivado de lo anterior, los responsables de los menores deberán vigilar el uso que estos últimos hagan de los Servicios, teniendo presente que los Servicios en cuestión están destinados a un público masivo.<br>
            La plena responsabilidad en la determinación de los contenidos y Servicios a los que acceden los menores de edad corresponde a los mayores a cuyo cargo se encuentran. Debido a que Internet hace posible el acceso a contenidos que pueden no ser apropiados para menores, se informa a los Usuarios que existen mecanismos, en particular programas informáticos de filtro y bloqueo, que permiten limitar los contenidos disponibles y, aunque no resultan infalibles, son de especial utilidad para controlar y restringir los materiales a los que pueden acceder los menores.<br>

            <h5 style="font-weight:bold"><br>3.5. Restricción en el Uso del Servicio</h5><br>
            El Usuario se compromete a utilizar la Página y los Servicios de conformidad con la legislación aplicable, los términos y condiciones de uso de la Página, las Condiciones Particulares de los Servicios, los avisos, reglamentos de uso, instrucciones, así como de acuerdo con la moral y las buenas costumbres generalmente aceptadas y el orden público, por lo que el Usuario deberá abstenerse de:<br>
            <br>
            (a) Acceder, alterar o destruir cualquier Contenido, que se relacione con el Servicio o que se obtenga a través de él, que no sea de su propiedad.<br>
            (b) Realizar actos que pudieran perjudicar a Grupo Lamhi y/o a cualquiera de sus afiliadas y/o subsidiarias y/o distribuidores y/o proveedores (denominados colectivamente “Colaboradores del Prestador”), o a cualquier Usuario, así como tampoco podrá usar el Servicio y/o los Contenidos como destino vinculado desde mensajes de correo electrónico masivo o mensajes comerciales no solicitados (“spam”); usar cualquier proceso o servicio automático para obtener acceso al  Servicio; utilizar cualquier medio no autorizado para modificar o redireccionar el Servicio, o intentar hacerlo; dañar, deshabilitar, sobrecargar o dificultar el Servicio (o la red o las redes conectadas al Servicio), o interferir en el uso y disfrute del mismo por parte de cualquier persona; o bien comercializar o redistribuir el Servicio o parte de los Contenidos.
            <br>
            (c) Descargar Contenidos si no se cuenta con la autorización expresa Grupo Lamhibr <br>
            (d) Reproducir, copiar, distribuir o poner a disposición o de cualquier otra forma comunicar públicamente en forma parcial o total del Servicio y/o los Contenidos, salvo que se cuente con la autorización escrita del titular de los derechos correspondientes;<br>
            (e) Suprimir, manipular o de cualquier forma alterar los datos o medios técnicos establecidos en el Servicio, que identifiquen la reserva de derechos de los mismos a favor de Grupo Lamhi y/o de los titulares de los Contenidos.<br>
            (f) Obtener e incluso intentar obtener los Contenidos empleando para ello medios o procedimientos distintos de los que, según los casos, se hayan puesto a su disposición a través del Servicio.<br>

            <h5 style="font-weight:bold"><br>3.6. Reconocimiento del Usuario </h5><br>
            El Usuario reconoce y acepta lo siguiente:<br>
            a) Que conoce la naturaleza de Internet, los términos y condiciones que regulan el Servicio y sus limitaciones, así como sus cualidades técnicas y los tiempos de respuesta para consultar, interrogar o transferir datos e información.<br>
            b) Que existen fenómenos sociales, políticos, culturales, económicos, entre otros, que pueden provocar en un momento dado que el uso de Internet, se incremente extraordinariamente, en forma tal que las condiciones de operación del Servicio se vean afectadas, ocasionando una saturación temporal que podría generar  lentitud en la ejecución del Servicio.<br>
            c) Que Internet es una red de redes, y la paralización de otra red puede reducir e incluso impedir la ejecución del Servicio.<br>
            d) Que algunos datos que circulan en Internet no tienen protección y que se pueden exponer y desviar, por lo que la difusión de códigos de acceso, códigos personales, números de cuentas bancarias, de tarjetas de crédito y más aún, de cualquier información confidencial por parte del Usuario, será por su cuenta y riesgo y bajo su exclusiva responsabilidad.<br>
            e) Que los datos que circulan en Internet, pueden estar sometidos a un reglamento en lo que se refiere a su uso o estar protegidas por un derecho de propiedad intelectual, por lo que el Usuario será el único responsable del uso de los Contenidos y/o datos que consulta, interroga o transfiere en Internet.<br>
            f) Que Grupo Lamhi no será responsable acerca de la precisión o calidad de los Contenidos, información o servicios que el Usuario pueda obtener o recibir a través del Servicio.<br>
            g) Que Grupo Lamhi no será responsable por cualquier daño y/o perjuicio que pueda sufrir el Usuario, entre otros de manera enunciativa más no limitativa, por pérdida de información, desconfiguración, retardos, no entregas, entregas erróneas o interrupción del Servicio.<br>
            h) Que Grupo Lamhi no será responsable por cualesquier retraso, eliminación, error en la entrega o falla, que le impida recibir cualquier tipo de Contenido.<br>
            i) Que el uso de cualesquiera Contenidos, información, datos, etc. obtenidos  a través del Servicio es por su cuenta y riesgo y bajo la exclusiva responsabilidad del Usuario.<br>
            j) Que el Usuario reconoce y acepta que cualquier Contenido, información, producto, servicio y/o aplicación disponible a través de Internet, diferentes de aquellos que sean identificados en forma clara y precisa como elementos que forman parte del Servicio, son proporcionados por otros usuarios y/o terceras partes, por lo que será responsabilidad de esa tercera parte mantener y soportar su información, productos, servicios y/o aplicaciones, y en consecuencia el Usuario reconoce que Grupo Lamhi no es ni será responsable en ningún momento por el uso, fallas, pérdida o errores en las mismas.<br>
            k) Que las páginas Web no creadas por Grupo Lamhi, así como algunos Contenidos pueden incluir imágenes, sonidos, textos u otros Contenidos que algunas personas pueden encontrar ofensivos o no aptos para menores de edad. Tales Contenidos son responsabilidad del tercero, proveedor de dicho Contenido, por lo que Grupo Lamhi no será responsable del control de los mismos y su acceso será por cuenta y riesgo del Usuario.<br>
            l) Que Grupo Lamhi no será responsable por daños causados por virus transmitidos a través de Internet.<br>
            m) Que Grupo Lamhi se reserva el derecho de: (i) finalizar cualquier sesión del  Servicio cuando se detecte la falta de uso de la misma por parte del Usuario y (ii) limitar el volumen de datos trasferidos.<br>
            n) Que Grupo Lamhi podrá suspender el Servicio en cualquier momento por disposición legal en caso de que el Usuario haga mal uso de la Página o realice prácticas que resulten contrarias a la ley o a las buenas costumbres. Lo anterior, independientemente de cualquier acción o reclamación que Grupo Lamhi y/o cualquier otro tercero pudiere llegar a ejercer en contra del Usuario responsable de llevar a cabo dichas conductas.<br>
            El Usuario reconoce el uso de Internet como un servicio público de carácter internacional, por lo que entiende y acepta que Grupo Lamhi no es responsable directo o indirecto de las acciones administrativas, técnicas o regulatorias que terceros apliquen en sus redes para proteger la integridad de su información, contenido, sistemas, aplicaciones, usuarios, etc.<br>
            <h5 style="font-weight:bold"><br>3.7. Links a Sitios de Terceros </h5><br>
            La Página cuenta con sitios enlazados tales como hipervínculos (links), anuncios publicitarios (banners), botones, directorios y/o herramientas de búsqueda, entre otros (“Sitios Enlazados”) que permiten al Usuario acceder a páginas de terceros que no  son propiedad de, ni operados por el Prestador, por lo que el Prestador no es responsable de la disponibilidad del material, accesibilidad o continuidad de los Sitios Enlazados, por el mantenimiento de los servicios, información, datos, archivos, productos y cualquier clase de material existente y por las obligaciones y ofertas existentes en dichos Sitios Enlazados.<br>
            Grupo Lamhi, sus subsidiarias y/o afiliadas no controlan, aprueban ni hacen propios los servicios, información, datos, archivos, productos y cualquier clase de material existente en los Sitios Enlazados. En consecuencia, el Usuario debe extremar la prudencia en la valoración y utilización de los servicios, información, datos, archivos, productos y cualquier clase de material existente en los Sitios Enlazados.<br>
            Derivado de lo anterior, el Usuario reconoce y acepta que Grupo Lamhi, sus subsidiarias y/o afiliadas quedan excluidas de cualquier responsabilidad por los daños y perjuicios que pudieran causarse o haber sido causados por la veracidad de la información o calidad de los servicios que se encuentren en los Sitios Enlazados.

            <h5 style="font-weight:bold"><br>4. NO LICENCIA</h5><br>
            El Servicio y los Contenidos en los que así se indique y que estén disponibles en la Página son propiedad exclusiva de Grupo Lamhi y/o de sus subsidiarias y/o afiliadas, y están protegidos por las leyes y tratados vigentes en materia de propiedad industrial e intelectual, por lo que el Usuario no está autorizado para realizar cualquier acto que tenga por objeto registrar u obtener la titularidad de los derechos de Propiedad Industrial e Intelectual del Servicio y/o de las Aplicaciones y/o Contenidos.<br>
            Mediante el uso de esta página, el usuario reconoce y acepta que Grupo Lamhi, sus subsidiarias y/o afiliadas, quedan excluidas de cualquier responsabilidad que pudiera ser causada por el uso no autorizado de las marcas u otros derechos de propiedad intelectual de terceros o contenidos en los sitios enlazados.<br>
            De igual manera, las eventuales referencias que se hagan en esta página a cualquier producto, servicio, proceso, Sitio Enlazado, hipertexto o cualquier otra información en la que se utilicen marcas, signos distintivos y/o dominios, el nombre comercial o el nombre del fabricante, suministrador, etc., que sean titularidad de terceros, en ningún momento constituirán, ni implicarán respaldo o recomendación alguna por parte del Prestador, sus subsidiarias y/o afiliadas y en ningún caso el Prestador, sus subsidiarias y/o afiliadas  se asignan propiedad ni responsabilidad sobre los mismos.<br>
            El Usuario deberá notificar inmediatamente a Grupo Lamhi de cualquier uso(s) no autorizado de los derechos de propiedad intelectual del Prestador y/o de sus subsidiarias y/o afiliadas.<br>
            En caso de que el Usuario contravenga lo dispuesto en la presente cláusula, será responsable del pago de daños y perjuicios ocasionados a Grupo Lamhi.<br>

            <h5 style="font-weight:bold"><br>5. EXCLUSIÓN DE GARANTÍAS Y DE RESPONSABILIDAD </h5><br>
            La información contenida en los Servicios puede incluir errores tipográficos, circunstancia que no será responsabilidad de Grupo Lamhi.<br>
            Grupo Lamhi no garantiza que el uso o los resultados del uso del Servicio o de los Contenidos serán correctos, precisos, puntuales o de otro modo, fidedignos.<br>
            La información transmitida por el Usuario a través del Servicio, será bajo su exclusiva responsabilidad, por lo que libera expresamente Grupo Lamhi, de cualquier responsabilidad derivada de accesos no autorizados, robo, daño, destrucción o desviación de la información, archivos o programas propiedad del Usuario que se relacionen de manera directa o indirecta con el Servicio.<br>
            El Usuario acepta expresamente que Grupo Lamhi no será responsable del acceso no autorizado a la Cuenta del Servicio o alteración de cualquier Material Enviado (como dicho término se define más adelante) así como de transacciones realizadas que guarden relación con los Sitios Enlazados.<br>
            El Usuario se obliga a sacar y mantener en paz y a salvo a Grupo Lamhi de cualquier reclamación, demanda o acción legal que pudiera presentarse en contra de Grupo Lamhi, derivadas de los hechos descritos en el párrafo precedente y, en general, de cualquier reclamación, demanda o acción legal que pudiera derivarse del uso del Servicio por parte del Usuario.<br>
            En ningún caso, Grupo Lamhi responderá por daños directos, indirectos, punitivos, incidentales, especiales, consecuenciales, ni de ningún otro tipo, incluidos, de manera enunciativa más no limitativa, los daños por pérdida de datos o de beneficios que se deriven o tengan relación con el uso del Servicio o de los Sitios Enlazados, con la demora o imposibilidad para poder utilizar el Servicio o cualquier otro tipo de servicio.<br>
            <h5 style="font-weight:bold"><br>6. PROTECCIÓN DE DATOS PERSONALES</h5><br>
            Para utilizar algunos de los Servicios, los Usuarios deben proporcionar previamente a Grupo Lamhi ciertos datos de carácter personal necesarios para la obtención de la Cuenta de Servicios (en adelante, los "Datos Personales"). Grupo Lamhi tratará automatizadamente los Datos Personales con las finalidades, así como bajo las condiciones, definidas en su Aviso de Privacidad publicada en la URL http://www.lamhi.com.mx/aviso-de-privacidad/.<br>
            Grupo Lamhi ha adoptado los niveles de seguridad de protección de los Datos Personales legalmente requeridos y procura instalar otros medios y medidas técnicas de protección adicionales. No obstante, el Usuario debe ser consciente de que las medidas de seguridad en Internet no son inexpugnables.<br>
            Grupo Lamhi puede utilizar Cookies cuando un Usuario navega por los sitios y páginas web de la Página. Las Cookies que se puedan utilizar en los sitios y páginas web de la Página se asocian únicamente con el navegador de un ordenador determinado (un Usuario anónimo), y no proporcionan por sí el nombre y apellidos del Usuario. Gracias a las Cookies, resulta posible que Grupo Lamhi reconozca los navegadores de los Usuarios registrados después de que estos se hayan registrado por primera vez, sin que tengan que registrarse en cada visita para acceder a las áreas y Servicios reservados exclusivamente a ellos. Las Cookies utilizadas no pueden leer los archivos cookie creados por otros proveedores. El Usuario tiene la posibilidad de configurar su navegador para ser avisado en pantalla de la recepción de Cookies y para impedir la instalación de Cookies en su disco duro. El Usuario deberá consultar las instrucciones y manuales de su navegador para ampliar ésta información. Para utilizar la Página, no resulta necesario que el Usuario permita la instalación de las Cookies enviadas por Grupo Lamhi, sin perjuicio de que en tal caso será necesario que el Usuario se registre cada vez que acceda a un servicio que requiera el previo registro.<br>
            Las Cookies que se utilizan en los sitios y páginas web de la Página pueden ser servidas por Grupo Lamhi, en cuyo caso se sirven desde los distintos servidores operados por éste, o desde los servidores de determinados terceros que nos prestan servicios y sirven las Cookies por cuenta Grupo Lamhi (como por ejemplo, las Cookies que se emplean para servir la publicidad o determinados Contenidos y que hacen que el Usuario visualice la publicidad o ciertos Contenidos en el tiempo, número de veces y forma predeterminados). Siempre que no haya activado la opción que impide la instalación de Cookies en su disco duro, el Usuario podrá explorar su disco duro siguiendo el manual de instrucciones y ayuda de su sistema operativo  para conocer con mayor detalle cada servidor desde donde se envían las Cookies.<br>
            <h5 style="font-weight:bold"><br>7. PROCEDIMIENTO EN CASO DE REALIZACIÓN DE ACTIVIDADES DE CARÁCTER ILÍCITO</h5><br>
            En el caso de que cualquier Usuario o un tercero considere que existen hechos o circunstancias que revelen el carácter ilícito de la utilización de cualquier Contenido y/o de la realización de cualquier actividad en las páginas web incluidas o accesibles a través de la Página, y, en particular, de la violación de derechos de propiedad intelectual o industrial (patentes, modelos y dibujos industriales, marcas y nombres comerciales, etc.) u otros derechos, deberá enviar una notificación escrita a Grupo Lamhi en la que se contengan los siguientes extremos: (a) datos personales del reclamante: nombre, dirección, número de teléfono y dirección de correo electrónico; (b) especificación de la supuesta actividad ilícita llevada a cabo en la Página y, en particular, cuando se trate de una supuesta violación de derechos, indicación precisa y concreta de los contenidos protegidos así como de su localización en las páginas web; (c) hechos o circunstancias que revelan el carácter ilícito de dicha actividad; (d) en el supuesto de violación de derechos, firma manuscrita o equivalente, con los datos personales del titular de los derechos supuestamente infringidos o de la persona autorizada para actuar en nombre y por cuenta de ésta; (e) declaración expresa y clara del carácter ilícito de la utilización de los contenidos o de la realización de las actividades descritas, bajo la responsabilidad del reclamante de que la información proporcionada en la notificación es exacta y veraz. .<br>
            <h5 style="font-weight:bold"><br>8. NOTIFICACIONES</h5><br>
            Todas las notificaciones y comunicaciones (en adelante, las "Notificaciones") por parte del Usuario a Grupo Lamhi se considerarán válidamente realizadas, para todos los efectos, cuando se dirijan al Servicio de Atención al Usuario de alguna de las siguientes formas: (a) Comunicación por medio de llamada telefónica al número +52 (998) 884 9641  (b) Envío por correo electrónico a la siguiente dirección: info@lamhi.com.mx.<br>
            Todas las Notificaciones por parte de Grupo Lamhi al Usuario se considerarán válidamente realizadas, para todos los efectos, cuando se realicen de alguna de las siguientes maneras: (a) Envío por correo electrónico a cualquiera de los correos que el Usuario dispone o pueda disponer como parte de cualquier otro servicio que Grupo Lamhi preste al Usuario; (c) Comunicación por medio de llamada telefónica al número de teléfono del Usuario, que este haya proporcionado previamente a Grupo Lamhi; (d)Mediante mensajes emergentes enviados durante la prestación de los Servicios por parte de Grupo Lamhi al Usuario.<br>
            A estos efectos, el Usuario manifiesta que todos los datos facilitados por él son ciertos y correctos, y se compromete a comunicar a Grupo Lamhi todos los cambios relativos a los datos de notificación.<br>
            <h5 style="font-weight:bold"><br>9. RETIRADA Y SUSPENSIÓN DE LOS SERVICIOS</h5><br>
            Grupo Lamhi podrá retirar o suspender en cualquier momento y sin necesidad de aviso previo la prestación de los Servicios a aquellos Usuarios que incumplan lo establecido en los presentes términos y condiciones de uso de la Página.<br>
            <h5 style="font-weight:bold"><br>10.   CUENTA DE SERVICIO DEL USUARIO</h5><br>
            El Usuario tendrá la opción de proporcionar Contenidos a la Página mediante su alta en la Cuenta de Servicio, quedando a discreción de Grupo Lamhi su exhibición en dicha Página.<br>
            En caso de que el Usuario dé de alta la Cuenta de Servicio en los términos establecidos en los presentes términos y condiciones de uso del portal, el Usuario en este acto acepta ser el único responsable de la veracidad de la información proporcionada y de todas las actividades que se realicen con su cuenta de Servicio, siendo directamente responsable del mal uso que se pudiera dar a dicha cuenta de Servicio.<br>
            <h5 style="font-weight:bold"><br>11. MODIFICACIONES. </h5><br>
            Grupo Lamhi se reserva el derecho de modificar o actualizar total o parcialmente en cualquier tiempo los presentes términos y condiciones de uso de la Página sin necesidad de notificar al Usuario en forma alguna. En caso de que el Usuario no esté de acuerdo con dichas modificaciones, el Usuario deberá suspender de manera inmediata el uso directo o indirecto del Servicio.<br>
            Asimismo, Grupo Lamhi está facultado para modificar en cualquier forma el Servicio, suspenderlo e incluso darlo por terminado, sin necesidad de notificar al Usuario y sin responsabilidad alguna. En tal circunstancia, cualquier tipo de derecho que tuviere el Usuario respecto del uso del Servicio quedará inmediatamente suspendido o terminado, según corresponda.<br>

            <h5 style="font-weight:bold"><br>12. PROMOCIONES Y PUBLICIDAD</h5><br>
            Grupo Lamhi puede agregar discrecionalmente la publicidad y material promocional que desee a la Página sin que por ello resulte responsable del contenido de dicha publicidad o material promocional.<br>

            <h5 style="font-weight:bold"><br>13. JURISDICCIÓN</h5><br>
            Para todo lo relacionado con la interpretación y ejecución de los presentes términos y condiciones de uso de la Página, Grupo Lamhi y el Usuario, con renuncia expresa a cualquier otro fuero, se someten al de los Juzgados y Tribunales de Cancún, Quintana Roo.<br>
            Para cualquier sugerencia o propuesta de colaboración escríbanos por correo electrónico a info@lamhi.com.mx <br>

          </blockquote>
        </div>
      </div>

    </div>
  </div>
</section>
<!-- End service Area -->

<?php
include ('footer.html');
?>